version: "3"

services:

  proxy:
    build: proxy
    image: nginx-proxy
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/tmp/default.conf
    environment: 
      - API_SERVER_ADDR=strapi:1337
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - strapi-stack
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3

  backend:
    image: strapi/strapi:3.6.8-alpine
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - strapi-stack
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - strapi-stack
    expose:
      - 5432
    
volumes:
  db-data:
secrets:
  db-password:
    file: config/password.lock
networks:
  strapi-stack:
    name: strapi-stack
    driver: bridge