version: "3.9"

services:

  pre:
    build:
      context: ../
      dockerfile: custom/Dockerfile
    image: ${REGISTRY:-docker.io}/${DOCKER_U:-libre}/${DOCKER_I:-strapi-custom}:${TAG:-v3}
